### ISSUE TITLE
User interactions are broken

### ISSUE THREAD

**Issue by castdrian** [MajeurAndroid/Android-Unofficial-Showdown-Client#1]
Opening a chat/challenging/receiving a challenge does not work, therefore the UI elements are quite misleading

**Comment by MajeurAndroid** [comment]
If you mean in the 'find user' popup, well, the buttons were just doing nothing 🤓. Private messages and challenges were planned, but not implemented yet.
Anyway, now this has been done!
See this commit 32ee188ae3ca202d38235beebbf7a07f932bfd82
