### ISSUE TITLE
Landscape mode support missing

### ISSUE THREAD

**Issue by castdrian** [MajeurAndroid/Android-Unofficial-Showdown-Client#2]
Devices such as the Nintendo Switch and other Android tablets operate mainly in landscape mode, the client forces portrait mode which is quite unhandy in these scenarios.

**Comment by MajeurAndroid** [comment]
Yes I am aware of that, but for now I cannot think about an efficient way of displaying everything needed for a battle in the limited height allowed by a phone device in landscape mode...
For tablets it's an easier job but if we support landscape mode, it has to be for all devices..
If you have some ideas or some blue prints of how the current layout elements can be packed into a landscape layout, I'd be really interested !!
By the way, thanks for reporting.

**Comment by castdrian** [comment]
So my skills lie in javaScript not in UI design or Java but regardless, here's a surgery I performed on a screenshot from my Galaxy S8:
![Screenshot_20200609-182006_Showdown_Client](https://user-images.githubusercontent.com/22133246/84177703-865e8300-aa83-11ea-8573-326af91faf77.jpg)

**Comment by castdrian** [comment]
also, probably known, but when a Zoroark unveils, it actually doesn't unveil

**Comment by MajeurAndroid** [comment]
I just finished implementing support for landscape on large screen devices ! See a429927

![framed_tablet](https://user-images.githubusercontent.com/11336456/86912932-21e42180-c11e-11ea-857b-b2dd912af761.png)

Thanks for your help.
