### ISSUE TITLE
Typo in "Smogon" in README

### ISSUE THREAD

**Issue by merkrafter** [MajeurAndroid/Android-Unofficial-Showdown-Client#3]
In your README file, under [credits](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client#credits), you wrote "Somogon" instead of Smogon. I don't know if thats intentional for some insider reason, but I just wanted to point that out. : )

**Comment by MajeurAndroid** [comment]
Fixed in 9637278. Thanks !
