### ISSUE TITLE
[1.0-alpha07c] Preview only shows 5 opposing Pokemon, even though they brought 6

### ISSUE THREAD

**Issue by ArkUmbra** [MajeurAndroid/Android-Unofficial-Showdown-Client#4]
![Image showing missing Kingdra](https://lh3.googleusercontent.com/sI689ZGovGCYxQLPfJYaepZs0Hs9jfhkOInMBd3d5rPJPtwyKgk4MMholpbBSJ-FNE-UJXcKJl3sxqINkJWTNywId8jPoAw926Mfm54UPUnRFz7Vsg4AGf8fVdCUJCmusJThJC4Aj5PW_7yceupi7JSWsi9DZMpgqkKOWk1D8pIj-yCXcWF1Nng_2n_GM4M5dbwkEPxfr8HDim2mq86iulqHlI9RH2dvzS5pDEY-u_W3Rllg3-p_srwDuEnk6k7gro5CgcPjtJVGDqrche7YaH3eHTslbZVlG21Qippx4hR4WAf6OvWbBTDZzgX6MOE9KwLOy5b1cgXZsQxiNT0YE_qxk14yvkXdkASZBVtAm_vtYU2w4gXgy41tRCUMxFnpZslQm9KrT0pm77M6eGxqloLWVRBvOSegaB707GSVHSIHVMRu68fSLT5rsai2oNn_9NG3NU7sxHBKMVKEBYsi6h_akAWeHMKwrdZ88gq20BfVRJBdADi2BmvhR1MBcNXue7UN7OP2R9qxk7aN8YbQ5YHNOgo9u-7FdJIr5ZgJgk68SkrcInvdJKnWCld-9YGE9YRXdxqzkUB_OcTqmF96q-Yia-KX0Y7Jxd9UjhkFa5QcTP0TpXxMqO0NC3lJskTQpjA_XdDx2MHGTY92u4tyuUqbKYxh53Um-ZPN3BKWNuW4Q2ScBihtCg=w457-h938-no?authuser=0)

Hello, I signed up to the alpha version of the app today. You've done some really great work with this app, and it's so much easier to use than the web client on mobile.

I have done a few Gen 8 OU battles, but then noticed this display issue. Unless I'm blind (very possible!), the preview doesn't show the opponent's Kingdra (it shows up in the list of 2d icons, and in the chat). This is the only time I have seen this issue so far.

I'm happy to look into it to try to replicate the issue in Android Studio, if you might have some issues of where to start looking. I assumed it was either a network problem, or maybe the icon had gone off screen or something?

Please let me know if you need more information. Thanks.

## General Info
**Replay**: https://play.pokemonshowdown.com/battle-gen8ou-1149589949 (obviously doesn't show the problem in the web client)
**App version**: 1.0-alpha07c
**Device**: Pixel3A (Android 10)

**Comment by ArkUmbra** [comment]
Also, this is just a general comment, but if there is a list of tasks/TODOs that you are accepting contributions on then I would be happy to take a look :bowing_man:

**Comment by MajeurAndroid** [comment]
Yes, I am aware of this bug, it has been reported multiple times in the past but I cannot figure out how to reproduce it.
I tried to ensure all image views are layed out correctly (See [this line in BattleLayout.kt](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/226cba4aa45dd3462238951bde7ebbd94f39643d/psclient/src/main/java/com/majeur/psclient/widget/BattleLayout.kt#L55)), but I'm not sure it's a layout issue.
I don't now why but when loading multiple sprites at the same time, the library in charge of loading sprites (Glide see [GlideHelper.java](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/master/psclient/src/main/java/com/majeur/psclient/io/GlideHelper.java)) sometimes fail to load them and load alternative fallback unanimated sprites. Maybe I should try this on a Wifi network or try to make connection timeouts longer 🤷‍♀️.

I'll try to put up a list of next things to work on ASAP, for now few bugfixes remain and once done I'll release a new version to public.

**Comment by MajeurAndroid** [comment]
> 
> 
> Also, this is just a general comment, but if there is a list of tasks/TODOs that you are accepting contributions on then I would be happy to take a look 🙇‍♂️

Done, see [here](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client#todo-list).

**Comment by ArkUmbra** [comment]
@MajeurAndroid Thanks! I'll take a look to see if there is anything I can assist with

**Comment by MajeurAndroid** [comment]
Now fixed ! 
Quick explanation: after a battle ends the ImageView used to display pokemon's sprite is cleared and its alpha is set to zero to smoothly animate battle's end. These views are also used to show the first pokemon during team previews, and the alpha wasn't reset to 1 so, a pokemon (or two if the previous battle was a double) was missing from team preview!
![Screenshot](https://user-images.githubusercontent.com/11336456/99078918-77927400-25bf-11eb-9f1b-2fcdc9bedbb2.jpg)

**Comment by ArkUmbra** [comment]
Nice job on finding the cause of the problem!! Thanks very much for fixing.
