### ISSUE TITLE
[Feature] Support for battle replays

### ISSUE THREAD

**Issue by ArkUmbra** [MajeurAndroid/Android-Unofficial-Showdown-Client#7]
First of all, thank you for writing up some of the TODOs. I decided to take a look at implementing the replay feature, as that seems like an isolated piece that I can work on.

I decided to make this thread to track progress / as a place to discuss the task, where required. Hopefully that's okay. I'll try to take a look at implementing what I can over the coming week.

# Notes
I took a look at the replays on the web client of Showdown today.  

Seems like if we append the '.log' to a URL then we get the full text log of the replay at once.

So, I think I might be able to extend the BattleFragment, to create a ReplayFragment class, and add the UI controls into that (and reuse the BattleFragment message handling). I think that because we're downloading the whole log file at once, we won't need to interact with the ShowdownService class - as such, the replay controls could just send each turn's worth of text to the fragment then.

At least... that's my current thinking. Will take a closer look over the following days to see if it's viable this way

**Comment by MajeurAndroid** [comment]
Nice, thanks for contributing ! I'm sure this feature will be really intersting to work on.
And yes, good idea, creating this thread will be much easier for us to discuss the feature im.

### Design
The client's UI was thinked out to be the simplest possible with the idea of splitting the app into distinct "sections" reflecting showdown's main features (battle, chat, teams). I think that, as long as replays are battles, they belong to the battle "section", so they should go in the `BattleFragment` to stick with the idea I just mentioned. Having an extra tab only for replays would be a bit redundent with the battle one.
Also, it will be much easier to implement in code where everything is already set up and working, and also a lot easier to maintain 😉.

### Implementation
To keep things easy and write fewest code possible, I just though about a flag in `BattleRoomMessageObserver` (kind of "isLive"), allowing you to display an additional toolbar with replay controls in it, if the flag is set to false. 
Also, I though `BattleRoomMessageObserver` could have a system where it delivers messages to itself using its `postMessage(ServerMessage)` method, the one `ShowdownService` uses to deliver messages coming from server. But maybe it would brake a bit its role of being an "observer"...
I think a "ReplayManager type" object would fit better. It could be in `ShowdownService` and deliver needed parts of the battle log directly to `BattleRoomMessageObserver`. It would be accessed in UI directly from `ShowdownService`, and would take care of setting up `BattleRoomMessageObserver` the same way it would be set up for a regular battle and deliver battle log parts. (With the idea of having a "fake" (or local) replay room with roomid set to the replay id, which would work really well with the existing code).
This way, you'll just have to create replays download logic in `ShowdownService`, the replay management object, and UI a bit, without altering much `BattleRoomMessageObserver`.

Ok maybe I wrote a bit to much 👀, but here are my thoughts !!

**PS:** Have a look [here](https://github.com/smogon/pokemon-showdown-client/blob/master/WEB-API.md#replays). More informations are available by using the .json to retireve replay's log.

**Comment by ArkUmbra** [comment]
> Ok maybe I wrote a bit to much eyes, but here are my thoughts !!
No, that's perfect, thanks! I don't know my way around the project too well yet, so it's nice to get detailed instructions :smiley: This should be enough for me to get something going.


> **PS:** Have a look [here](https://github.com/smogon/pokemon-showdown-client/blob/master/WEB-API.md#replays). More informations are available by using the .json to retireve replay's log.

Ah yes, I had already found that very helpful page! Actually, that's how I found the '.log' format. Initially I thought the '.json' response contained less information, but it seems I was wrong. So I think I'll go ahead with the JSON version, as you suggested, especially as it gives nice easy access to player names, ids, etc.

Comparison example
https://replay.pokemonshowdown.com/smogtours-ou-39893.log
https://replay.pokemonshowdown.com/smogtours-ou-39893.json

## Task for now
I think using the information you've given me, I will first try to get a working replay using a hardcoded URL, so we can see how it looks when running. Then we can discuss UI, and all that. 

For a later step/task, I was thinking it might be nice to have a way to 'favorite' certain replays, or store them locally, etc, so that they can be selected from within the app. But I'm not really sure where we'd put that sort of thing :)

**Comment by MajeurAndroid** [comment]
> 
> ## Task for now
> 
> I think using the information you've given me, I will first try to get a working replay using a hardcoded URL, so we can see how it looks when running. Then we can discuss UI, and all that.

Yes, definitely the way to go! 

> 
> For a later step/task, I was thinking it might be nice to have a way to 'favorite' certain replays, or store them locally, etc, so that they can be selected from within the app. But I'm not really sure where we'd put that sort of thing :)

Sure, we'll see this when we will have figured out UI for replays.

Do not hesitate if you have any doubt or any question on the project 😉.

**Comment by ArkUmbra** [comment]
Okay, so I got the first draft of replays working. 

It downloads the (currently hardcoded) URL, then automatically sends the messages to the observers. Currently it is just using a simple timer thread to send a new line from the log roughly every half a second.

I also added a simple dummy UI control panel, but it doesn't really do anything yet.

Here is a screen recording (Please ignore the out of place 'View Replay' button. I just put it there for testing) https://drive.google.com/file/d/1FaYtTb7j9G-FV45TjxKXG1KlLmjzW0lH/view?usp=sharing

## Things I still need to update
- Currently the timing of the messages looks a bit weird at the start of the battle. I have some (currently commented out) code to parse the log into distinct blocks (init, team preview, turn1, turn2, etc), so I could send the set up messages (joins, rules, etc) to observers a bit quicker, then add slight sleeps between each turn so it's a bit more natural to watch. 
- Fix the 'You are currently in' button text on the home fragment to say 'Replay xyz'. Currently it just says 'GEN8RANDOMBATTLE'
- When the replay finishes, the room still stays open. This means that you can't search for a game after watching a replay!
- In order to decide which UI controls to show, I added a 'onSetRoomType' callback to BattleRoomMessageObserver.UiCallbacks, which accepts an enum of values 'LIVE' or 'REPLAY'. Need to make sure the correct room type is set when going from replay to battle, etc.

## Questions for now
- What kind of UI controls do we want? If we **really** want a 'back one step/turn' button, I think we'd have to store the game 'state' for each turn (like this kind of thing http://www.blackwasp.co.uk/Memento.aspx) so that we could 'undo' the state. On the other hand, I think 'pause/resume', and 'back to start' would be quite easy.
- On this note, viewing a replay also 'behaves' like a battle so you can't search for a game when a replay is running. How do you think this should work? Allow the user to search for a game, but show a dialog saying that it will cancel the replay? Or require the user to wait until the replay is finished / force them to 'cancel' the replay in the battle fragment, etc.

I am open to any thoughts :)

**Comment by MajeurAndroid** [comment]
> Okay, so I got the first draft of replays working.
> 
> It downloads the (currently hardcoded) URL, then automatically sends the messages to the observers. Currently it is just using a simple timer thread to send a new line from the log roughly every half a second.

> * Currently the timing of the messages looks a bit weird at the start of the battle. I have some (currently commented out) code to parse the log into distinct blocks (init, team preview, turn1, turn2, etc), so I could send the set up messages (joins, rules, etc) to observers a bit quicker, then add slight sleeps between each turn so it's a bit more natural to watch.
>
Nice! You do not need any timing management here, you can feed the battle observer with all the log at one time. Delays between commands are handled in [`BattleRoomObserver`](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/master/psclient/src/main/java/com/majeur/psclient/service/observer/BattleRoomMessageObserver.kt) by posting to  [`ActionQueue`](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/master/psclient/src/main/java/com/majeur/psclient/service/ActionQueue.kt) which manages invoking Ui callbacks at the right time. You can see an example of such behaviour with almost every battle command, [for example with a move command](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/3b236f09f0301dbe343ff5e1396b038a87afb0c9/psclient/src/main/java/com/majeur/psclient/service/observer/BattleRoomMessageObserver.kt#L158).
If you post all the log in one time, it will invoke every action instantly until the last turn in the given log part, turn that will be invoked as usual with delays (see [this line](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/3b236f09f0301dbe343ff5e1396b038a87afb0c9/psclient/src/main/java/com/majeur/psclient/service/ActionQueue.kt#L30)). This is here to avoid waiting for each turn to append when joining an already started battle. Maybe we should change this behaviour for replays and let it loop normally, or have a direct control of this queue.

> I also added a simple dummy UI control panel, but it doesn't really do anything yet.
> 
I think these commands, at this place (in the `ExtraActionLayout`), will fit perfectly. Pause, next/previous turn and battle start/end should be enough.

> 
> * Fix the 'You are currently in' button text on the home fragment to say 'Replay xyz'. Currently it just says 'GEN8RANDOMBATTLE'
> * When the replay finishes, the room still stays open. This means that you can't search for a game after watching a replay!
> 
This is weird, normally this is updated depending on which room you are as per the server... (see [here](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/3b236f09f0301dbe343ff5e1396b038a87afb0c9/psclient/src/main/java/com/majeur/psclient/service/observer/GlobalMessageObserver.kt#L208))

> * In order to decide which UI controls to show, I added a 'onSetRoomType' callback to BattleRoomMessageObserver.UiCallbacks, which accepts an enum of values 'LIVE' or 'REPLAY'. Need to make sure the correct room type is set when going from replay to battle, etc.
> 
Perfect.
 
> * What kind of UI controls do we want? If we **really** want a 'back one step/turn' button, I think we'd have to store the game 'state' for each turn (like this kind of thing http://www.blackwasp.co.uk/Memento.aspx) so that we could 'undo' the state. On the other hand, I think 'pause/resume', and 'back to start' would be quite easy.
> 
There is not that much of things to update when changing turn (see vars from [line 39 to 43](https://github.com/MajeurAndroid/Android-Unofficial-Showdown-Client/blob/3b236f09f0301dbe343ff5e1396b038a87afb0c9/psclient/src/main/java/com/majeur/psclient/service/observer/BattleRoomMessageObserver.kt#L39)), the real issue will be to know in battlelog's `TextView` which text parts will be removed when seeking through turns. Using invisible text spans at each turn can do the trick (also maybe we'll have to switch to an unediatble EditTextView, because TextView do not implement enough code to allow to partially remove text..).

I'll think a bit on how to store each player pokemons, weather etc;.. state for each turn. Maybe we should find out how this is done in official client.

> * On this note, viewing a replay also 'behaves' like a battle so you can't search for a game when a replay is running. How do you think this should work? Allow the user to search for a game, but show a dialog saying that it will cancel the replay?
>
Yes, I think this is the best behaviour.

**Comment by ArkUmbra** [comment]
Just an small update. 

I followed your suggestion to make better use of ActionQueue instead of my own timing, and it looks so much better now. Thanks! I had to add a couple more methods there just to give me control over how it looped (e.g. if the current data is a replay, it doesn't skip to the last turn now).

Currently I'm working handling search for battles after/during replay. As we discussed, I've added a dialog to the search for battles box which will display when a replay is running.

At the moment, I've got to properly 'clean' the replay data out / reset the room so it is ready for a normal battle. Currently I get a crash when searching for a battle after a replay, so I need to take a look at that :^) 

Didn't get as much time as I would've liked on it this weekend, but I'll try to fix that up and post another video soon.

**Comment by MajeurAndroid** [comment]
> I followed your suggestion to make better use of ActionQueue instead of my own timing, and it looks so much better now. Thanks! I had to add a couple more methods there just to give me control over how it looped (e.g. if the current data is a replay, it doesn't skip to the last turn now).
> 
So cool, I'm glad this feature is getting there !

> At the moment, I've got to properly 'clean' the replay data out / reset the room so it is ready for a normal battle. Currently I get a crash when searching for a battle after a replay, so I need to take a look at that :^)
> 
To reset the room, normally you just have to do a `battleFragment.observedRoomId = null`, as it will automatically trigger an onRoomDeinit() call. If handling room states and/or correct behaviour when starting or leaving a replay room are giving you troubles, I can do that part (I mean if you want, if you understood rooms init and deinit I think u should be ok).

Also, if it causes too much complications, we can in first place leave the "rewind"/"previous turn" feature for later, as it implies a lot of changes. If you managed to implement it, or have some ideas, that's nice! 🤷‍♀️.

Once done, you can PR even if you're not 100% sure, that way I'll be able to see a bit the code you wrote and to give you some tips.
Keep up the good work bud!!

**Comment by ArkUmbra** [comment]
Just made a draft PR with the current progress. If you could take a quick look when you have time, that would be much appreciated :rocket: Thank you

Also, here are a couple more screen recordings of the current behaviour. Sometimes it's a little hard to see what I clicked, but hopefully it's somewhat understandable!

- [Next turn control](https://drive.google.com/file/d/1dXX1Hh4AYRDi3OYsui_LLTVvrZ5pIRrO/view?usp=sharing)
- [Search for battle during replay](https://drive.google.com/file/d/10rWC4eUFx89HVYsLhiNPzjFEAA7xazDp/view?usp=sharing)

**Comment by MajeurAndroid** [comment]
Really nice 👏👏
I have reviewed the PR.

**Comment by ArkUmbra** [comment]
I just updated the PR as per your suggestions. Many thanks again for your time reading through. :bowing_man: 

I thought I would address your review comments first before adding anything more to this, so now that is done, UI questions!

You suggested we could add a 'bottom sheet' like with the team builder, so I will take a look at that. Seems like the replay search API is quite simple so it shouldn't be too hard. Do you foresee this living on the 'home' fragment, or somewhere else?

**Comment by MajeurAndroid** [comment]
> Do you foresee this living on the 'home' fragment, or somewhere else?

No, I'm ok with a "replays" button below the "find a user" one. I'm just thinking about splitting the work in two different PRs (the first one that adds support for replays and the second one for replays searching UI). This to make things easier and to avoid us having an infinite PR with comments, reviews etc 😉
Could you make your PR non draft so I can merge it, and then open a new one for the "replay searching" feature ? 

PS: sorry for the late answer, I did not have access to my computer !!

**Comment by ArkUmbra** [comment]
Sure, that makes sense to me :) 

I just pushed a small change to hide the dummy search replay button on the home screen, and then opened up the PR. Please feel free to merge / do any reorganising you would like. And thanks once again for your patience and guidance through the review.

I suspect I won't get much time to work on the UI changes this week as it's holiday season here in Tokyo, but I'll get on it as soon as I can! If the preference takes you, I also have no problem if you want to take a crack at doing it yourself. Otherwise, I will get to it when I am next able to! :smile:

**Comment by MajeurAndroid** [comment]
I just tested the replay feature, and wow, it's really nice and works well ! Thanks alot for your time and your good work, if you have anything in mind, or want to contribute again to the project, you're more than welcome 😀😀.

Also, I just implemented UI for replay search ! (see: d41bec3)
